export const keys = [
  'música sertaneja as mais tocadas',
  'música sertaneja as melhores',
  'top 100 as mais tocadas',
  'músicas sertanejas',
  'músicas melhores sertanejas',
  'as melhores do sertanejo',
  'sertanejo as mais tocadas',
  'as mais sertanejas',
  'sertanejo músicas',
  'as mais tocadas do sertanejo',
  'o melhor do sertanejo',
  'top sertanejo',
  'as melhores músicas sertanejas',
  'sertanejas mais tocadas',
  'as melhores sertanejas',
  'melhores sertanejo',
  'músicas sertanejas mais tocadas',
  'sertanejos mais tocados',
  'as melhores sertanejo',
  'as melhores de sertanejo',
  'as 100 melhores sertanejas',
  'sertanejo top',
  'mais tocadas sertanejo',
  'as melhores músicas de sertanejo',
  'melhor do sertanejo',
  'Gusttavo lima',
  'modao sertanejo',
  'ze neto e cristiano',
  'Henrique e juliano',
  'esquenta sertanejo',
  'playlist modao',
  'moda sertaneja',
  'luan santana',
  'zeze di camargo',
  'zeze di Camargo e luciano',
  'zeze antigas',
  'Zeze rustico',
  'sertanejo',
  'os melhores sertanejos',
  'playlist Spotify',
  'playlist de música',
  'sertanejo bom',
  'sertanejo antigo',
  'musicas sertanejas',
  'ouvir música sertaneja',
  'musica sertaneja',
  'música sertaneja músicas',
  'música sertaneja antigas',
  'tocar música sertaneja',
  'musica caipira',
  'música sertanejo',
  'ouvir musicas sertanejas',
  'musicas sertanejas antigas',
  'música sertaneja antiga raiz',
  'moda de viola',
  'músicas sertanejas antigas',
  'quero ver música sertaneja',
  'as melhores sertanejas antigas',
  'quero ouvir música sertaneja raiz',
  'quero música sertaneja',
  'sertanejo raiz as melhores',
  'a música sertaneja',
  'música sertaneja de raiz',
  'sertaneja raiz',
  'música sertaneja raiz',
  'música sertaneja raiz as melhores',
  'musica sertaneja 2020',
  'música de sertanejo',
  'música sertaneja romântica',
  'moda sertaneja raiz',
  'musica caipira raiz',
  'ouvir música sertaneja antiga',
  'moda de viola gospel',
  'musica sertanejas mais tocadas',
  'ouvir música sertaneja online',
  'modão sertanejo',
  'sertanejas antigas mais tocadas',
  'musicas sertanejas atuais',
  'músicas caipiras',
  'musicas raizes',
  'modão sertanejo raiz',
  'top 10 sertanejo',
  'quero ouvir moda de viola',
  'musica raiz',
  'sertanejo as melhores',
  'quero ouvir música sertaneja',
  'YouTube',
] as const;
